version: "3"

services:
  backend:
    build: ./krok_power_backend
    volumes:
      - ./krok_power_backend/:/krok_power_backend # maps host diretory to internal container directory
    working_dir: /krok_power_backend/
    command: sh entrypoint.sh
    environment:
      - DEBUG=True
  nginx:
    image: nginx:latest
    ports:
      - 89:8080
    volumes:
      - ./nginx/nginx-proxy-just-front.nginx:/etc/nginx/conf.d/default.conf:ro
      - ./krok_power_backend/static:/var/www/krok_power_backend/static
    depends_on:
      - backend
