version: "3"

services:
  backend:
    build: ./krok_power_backend
    volumes:
      - ./krok_power_backend/:/krok_power_backend # maps host diretory to internal container directory
    working_dir: /krok_power_backend/
    command: sh entrypoint.sh
  frontend:
    image: node:10.16.3
    command: sh entrypoint.sh
    working_dir: /krok_power_frontend
    volumes:
      - ./krok_power_frontend/:/krok_power_frontend
  nginx:
    image: nginx:latest
    ports:
      - 89:8080
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./krok_power_frontend/build:/var/www/krok_power_frontend
    depends_on:
      - backend
