version: "3"

services:
  django:
    build: ./krok_power_backend
    container_name: django
    volumes:
      - ./krok_power_backend/:/krok_power_backend
    working_dir: /krok_power_backend/
    command: sh entrypoint.sh
    networks:
      - app-network
    environment:
      - DEBUG=False

  frontend:
    image: node:10.16.3
    container_name: frontend
    command: sh entrypoint.sh
    working_dir: /krok_power_frontend
    volumes:
      - ./krok_power_frontend/:/krok_power_frontend

  nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: nginx
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx-proxy.nginx:/etc/nginx/conf.d/default.conf:ro
      - ./krok_power_frontend/build:/var/www/krok_power_frontend
      - ./krok_power_backend/static:/var/www/krok_power_backend/static
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - django
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
